require 'sinatra/base'
require 'sinatra/reloader'
require 'sinatra/activerecord'
require 'sinatra/flash'
require_relative 'models/user'
require_relative 'controllers/application_controller'
require_relative 'controllers/home_controller'
require_relative 'controllers/users_controller'
